$version: "2"

namespace com.cloud.provider.amqp

/// AMQP/RabbitMQ binding metadata for an operation.
///
/// The tutorial routes every command to a RabbitMQ direct exchange named
/// `computing`; the command name is used as the routing key. This trait keeps
/// the Smithy model protocol-agnostic while preserving those broker bindings.
@trait(selector: "operation")
structure amqp {
    /// RabbitMQ exchange to publish the command to.
    @required
    exchange: AmqpExchangeName

    /// Routing key used by the direct exchange. In the tutorial this is the
    /// command name, for example `create-vm` or `list-vms`.
    @required
    routingKey: AmqpRoutingKey

    /// Delivery pattern used by the worker fleet.
    @required
    target: AmqpTarget

    /// Queue name when the operation targets a known queue. Exclusive worker
    /// queues are generated by RabbitMQ and therefore usually omitted here.
    queue: AmqpQueueName

    /// Reply-to behavior used by request/reply operations.
    reply: AmqpReplyConfig
}

@length(min: 1, max: 255)
@pattern("^[A-Za-z0-9._:-]+$")
string AmqpExchangeName

@length(min: 1, max: 255)
@pattern("^[A-Za-z0-9._:-]+$")
string AmqpRoutingKey

@length(min: 1, max: 255)
@pattern("^[A-Za-z0-9._:-]+$")
string AmqpQueueName

/// How a command is delivered to workers.
enum AmqpTarget {
    /// A competing-consumer queue; any worker with capacity can process it.
    COMPETING = "competing"

    /// Broadcast to each worker's exclusive queue.
    BROADCAST = "broadcast"

    /// A command for the worker that owns the VM. In the tutorial this is
    /// implemented by broadcasting and ignoring the worker-level not-found
    /// failures, but the model keeps the intended semantic explicit.
    OWNER_WORKER = "owner-worker"

    /// Operation is composed from other AMQP commands rather than having its
    /// own first-class tutorial command.
    DERIVED = "derived"
}

structure AmqpReplyConfig {
    /// True when the client uses RabbitMQ Direct Reply-To
    /// (`amq.rabbitmq.reply-to`).
    directReplyTo: Boolean

    /// True when the caller expects at least one response envelope.
    required: Boolean

    /// Client-side collection window for replies.
    timeoutSeconds: Integer

    /// Whether multiple worker replies may be returned.
    multipleResponses: Boolean
}
